#!/bin/bash -eu
port="$(modelctl get http.port)"
host="$(modelctl get http.host)"
mmproj_args=()
if [ -n "${MMPROJ_FILE:-}" ]; then
  mmproj_args=(--mmproj "$MMPROJ_FILE")
fi
verbose="$(modelctl get verbose)"
EXTRA_ARGS=()
if [ "${verbose}" = "true" ]; then EXTRA_ARGS+=(--verbose); fi
set -x
exec llama-server \
  --model "$MODEL_FILE" \
  --alias "$MODEL_NAME" \
  "${mmproj_args[@]}" \
  --port "$port" \
  --host "$host" \
  --no-warmup \
  "${EXTRA_ARGS[@]}" \
  "$@"
