name: Agentic Snap Test

on:
  schedule:
    - cron: "50 6 * * 3" # Weekly on Wednesday
  push:
    branches:
      - IENG-2625-increase-runner-ram-for-agentic-tests # TODO: remove before merging
  workflow_dispatch:

jobs:
  ai-test:
    # GitHub-hosted runners have 16GB RAM, which is not enough for this model
    runs-on: [self-hosted, large, amd64]
    steps:
      - name: Run test
        uses: canonical/inference-snaps-dev/.github/actions/agentic-test@v2
        with:
          snap-name: glm-4-7-flash
          snap-channel: beta
          create-issues: false # TODO: set back to true before merging
          openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY }}
          issue-create-token: ${{ secrets.ISSUE_CREATE_TOKEN }}
