#!/bin/bash -eu
tag="snap.$SNAP_INSTANCE_NAME.hook.install"
exec 1> >(tee >(logger --tag=$tag))
exec 2> >(logger --stderr --priority error --tag=$tag)

modelctl set --package verbose="false"
modelctl set --package http.port="8348"
modelctl set --package http.host="0.0.0.0"
modelctl set --package webui.http.port="8349"
modelctl set --package webui.http.host="127.0.0.1"

ln -sf /var/lib/snapd/hostfs/usr/lib/wsl/lib $SNAP_COMMON/usr/lib/wsl/lib
ln -sf /var/lib/snapd/hostfs/usr/lib/wsl/drivers $SNAP_COMMON/usr/lib/wsl/drivers

if snapctl is-connected hardware-observe; then
    modelctl use-engine --auto --assume-yes --verbose
elif lscpu -V &> /dev/null; then
    echo "Able to access hardware info without hardware-observe interface connection: assuming dev mode installation."
    modelctl use-engine --auto --assume-yes --verbose
else
    echo "hardware-observe interface not auto connected. Skip auto engine selection."
fi
